require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/url_lists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UrlList. As you add validations to UrlList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UrlList.create! valid_attributes
      get url_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      url_list = UrlList.create! valid_attributes
      get url_list_url(url_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_url_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      url_list = UrlList.create! valid_attributes
      get edit_url_list_url(url_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UrlList" do
        expect {
          post url_lists_url, params: { url_list: valid_attributes }
        }.to change(UrlList, :count).by(1)
      end

      it "redirects to the created url_list" do
        post url_lists_url, params: { url_list: valid_attributes }
        expect(response).to redirect_to(url_list_url(UrlList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UrlList" do
        expect {
          post url_lists_url, params: { url_list: invalid_attributes }
        }.to change(UrlList, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post url_lists_url, params: { url_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested url_list" do
        url_list = UrlList.create! valid_attributes
        patch url_list_url(url_list), params: { url_list: new_attributes }
        url_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the url_list" do
        url_list = UrlList.create! valid_attributes
        patch url_list_url(url_list), params: { url_list: new_attributes }
        url_list.reload
        expect(response).to redirect_to(url_list_url(url_list))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        url_list = UrlList.create! valid_attributes
        patch url_list_url(url_list), params: { url_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested url_list" do
      url_list = UrlList.create! valid_attributes
      expect {
        delete url_list_url(url_list)
      }.to change(UrlList, :count).by(-1)
    end

    it "redirects to the url_lists list" do
      url_list = UrlList.create! valid_attributes
      delete url_list_url(url_list)
      expect(response).to redirect_to(url_lists_url)
    end
  end
end
